### ISSUE TITLE
allow port 0

### ISSUE THREAD

**Issue by kevinburke** [kevinburke/godocdoc#1]
from @peterhellberg: "Yes, but not `0`"

**Comment by peterhellberg** [comment]
If you decide to do anything related to binding to an unknown port, then you might want to use this trick from the [freeport](https://github.com/phayes/freeport) package: 

```go
func GetPort() int {
	addr, err := net.ResolveTCPAddr("tcp", "localhost:0")
	if err != nil {
		panic(err)
	}

	l, err := net.ListenTCP("tcp", addr)
	if err != nil {
		panic(err)
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port
}
```

https://github.com/phayes/freeport/blob/e7681b37614941bf73b404e0caa37f19e33b5fed/freeport.go#L8-L20
